import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/Header";
import { ThemeProvider } from "@mui/material/styles";
import { myTheme } from "@/mui-theme";
import { Bitter } from "next/font/google";
import "swiper/css";
import NextAuthSessionProvider from "@/session-provider";

export const metadata: Metadata = {
  title: "Clothey",
  description: "Generated by create next app",
};

const bitter = Bitter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bitter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={myTheme}>
            <NextAuthSessionProvider>
              <Header />
              {children}
              <Footer />
            </NextAuthSessionProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
